### ISSUE TITLE
Check the database initiation

### ISSUE THREAD

**Issue by antydemidov** [antydemidov/Bookshelf#14]
### Tasks

- [ ] Review SQL requests.
- [ ] Check if the database is initializing correctly.
- [ ] Check if the database is updating correctly.

### Expected behavior

- From scratch the database must be initialized correctly.
- When the update is available, the database must be updated correctly, e.g., new fields must be added.
